spring:
  cloud:
    config:
      server:
        git:
          uri: ${configserver.git.url:C:\work\BMOCAT\SourceCode\ConfigFiles}
    bus:
      destination: configXchange
  rabbitmq:
    host: ${rabbitmq.host:192.168.99.100}
    port: ${rabbitmq.port:5672}
server:
  port: 8888

management:
  endpoints:
    web:
      exposure:
        include: "*"

